from abc import ABC, abstractmethod
import json
import time
from google import genai

from Formatter import GemmaFormatter
from LLM import GemmaLLM

# The Actor class represents the actor module of an agent.
# It is responsible for generating the agent's response given the current history of the negotiation.
class Actor():
    def __init__(self, description, client):
        self.__description = description
        self.client = client
        self._formatter = client.get_formatter()
        self._initPrompt = f"\n".join(self.getDescription()['rules'])
    
   

    # The ask method takes the current history of the negotiation and an optional hint, 
    # and generates the agent's response using the LLM client.
    # Before generating the response, it formats the history and the rules using the formatter of the LLM client.
    # All the messages generated by the same role, are considered model messages, otherwise they are considered user messages.
    def ask(self, data, hint="") -> str:
        newMessages = []
        for message in data:
            if self.getRole().lower() == message['role'].lower():
                newMessages.append(
                    self._formatter.modelMessage(message['text'])
                )
            else:
                newMessages.append(
                    self._formatter.userMessage(message['text'])
                )

        newMessages.append(self._formatter.ruleMessage(self._initPrompt))
        if hint != "":
            newMessages.append(self._formatter.ruleMessage(f"{hint}"))
        
        response = self.client.generate(newMessages)
        return response 
    
    def getRole(self) -> str:
        return self.__description['role']

    def getDescription(self):
        return self.__description
    

# NULL ACTORS, used for testing purposes. 
# They do not generate any response, but they can be used to compute the DI score of the messages generated by 
# the other agent.
class NullBuyerActor(Actor):
    def __init__(self):
        super().__init__({"role": "Buyer"}, GemmaLLM())

    def getDescription(self):
        return {"rules": [], "role": "Buyer"}
    
    def ask(self, data, hint="") -> str:
        return ""

    def getRole(self) -> str:
        return "Buyer"
    
class NullSellerActor(NullBuyerActor):
    def getRole(self) -> str:
        return "Seller"